### ISSUE TITLE
GetShortFileName Method throws "Index and length must refer to a location within the string"

### ISSUE THREAD

**Issue by sobuctb** [Sicos1977/MsgKit#1]
GetShortFileName Method in [this file](https://github.com/Sicos1977/MsgKit/blob/master/MsgKit/Attachments.cs#L333) doesn't checks string length:
`name = name.Substring(0, 6).ToUpperInvariant() + "~1";`
and
`name += "." + extension.Substring(1, 3).ToUpperInvariant();`
and throws **Index and length must refer to a location within the string** for filenames like that "te.st"

I think it should be like that:
`name = (name.Length > 8 
                    ? name.Substring(0, 6) + "~1" 
                    : name).ToUpperInvariant();`
and
`name += "." + (extension.Length > 3 ? extension.Substring(1, 3) : extension.TrimStart('.')).ToUpperInvariant()`

**Comment by Sicos1977** [comment]
I added your fixes... thanks
