### ISSUE TITLE
FileLoadException: Could not load file or assembly 'OpenMcdf, Version=2.1.0.33051

### ISSUE THREAD

**Issue by larsm11** [Sicos1977/MsgKit#10]
When loading NuGet package 1.1.1, the following problem occured when running the sample code from the Read.me file.

FileLoadException: Could not load file or assembly 'OpenMcdf, Version=2.1.0.33051, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044).

Any idea on how to deal with this.

**Comment by Sicos1977** [comment]
I made a signed version of OpenMcdf and added that to a new nuget package

**Comment by Timothyoverton** [comment]
Fantastic! I downgraded to version 1.0.0 of MsgKit because of this error, I'll try the new version. Thanks for your prompt reply.
