### ISSUE TITLE
the email body will display garbled characters if it is too long.

### ISSUE THREAD

**Issue by yourng** [Sicos1977/MsgKit#103]
When email.BodyHtml is too long, the returned value will show garbled characters. The body contains some HTML

**Comment by Sicos1977** [comment]
Do you have an example?

**Comment by yourng** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Sicos1977** [comment]
?

**Comment by yourng** [comment]
> ?
 I have resolved it. Thank you very much.
