### ISSUE TITLE
how to send msg file after make it

### ISSUE THREAD

**Issue by MohamedHussen** [Sicos1977/MsgKit#104]
when i create new Email and open .msg file i cannot send it

**Comment by Sicos1977** [comment]
Generate it as a draft e-mail, then you can sent it.

**Comment by MohamedHussen** [comment]
could you give me the sample code

**Comment by Sicos1977** [comment]
What do you mean with readonly?

**Comment by MohamedHussen** [comment]
Could you give me the sample code to Generate the email as draft

**Comment by Sicos1977** [comment]
The draft flag is in the constructor on the email object

**Comment by MohamedHussen** [comment]
Thank you
