### ISSUE TITLE
Attaching files to email working but not releasing file, attachment streams need to be at position zero

### ISSUE THREAD

**Issue by Timothyoverton** [Sicos1977/MsgKit#11]
Hi Sicos, 

I've tried to attach files to an email from the file system, I then save the email, that works and can move the email to its final destination, however when I go to delete the files, windows says the files are still in use. The process of attaching the file to the email is holding the file open, you must have a dispose class that hasn't been called? Only after my application is closed, can I delete the files.

I switched to using streams which was probably better for my application but I had issues creating attachments from a stream, the attachments were empty, the fix was to ensure the stream position was set to zero before passing it through to the email object. I would have thought that your code should check the stream is at position zero?

Let me know if you want anymore information.

Many thanks,
Tim

**Comment by Sicos1977** [comment]
There is no check to see if the stream is at position zero, the reason for this is that somebody for example can have a stream with file information before it. If I reset the stream I don't know if I get the correct data. There could be a reason why the stream does not start at zero.

**Comment by Sicos1977** [comment]
I just checked my example program but nothing is keeping a lock on the image that I added to the created MSG file. Did you use using like I did in the screenshot below?

![image](https://user-images.githubusercontent.com/6692947/28131060-01b712a6-6739-11e7-9f38-811c09636ffd.png)

**Comment by Timothyoverton** [comment]
Hi Sicos, yes I followed your example exactly. Try this, while you have the msg file open after the process start, keep your demo application running, now try to delete peterpan.jpg - you won't be able to...(sorry for my late reply)

**Comment by Timothyoverton** [comment]
It makes sense now, why you don't reset the stream position, thanks for the clarification.
