### ISSUE TITLE
Creating a MSG - how to use AddProperty-method?

### ISSUE THREAD

**Issue by SigiKoh** [Sicos1977/MsgKit#114]
[https://github.com/Sicos1977/MsgKit/issues/78](url)
i am still struggling with the same problem ☹only one hint is too little for a beginner.
is it possible, that you tell me the code I need?
or any chance of getting a version of MsgKit, which is able to set the „Billing“-Property?
i would pay for it?

**Comment by Sicos1977** [comment]
I'll try to look into it tomorrow. I'm not home at the moment

**Comment by Sicos1977** [comment]
What exactly do you want to do?

**Comment by SigiKoh** [comment]
hi,

i need to add the property „billinginformation“, but could not manage it with your hint…

 

using (var email = new Email( 

            new Sender(SenderTextBox.Text, string.Empty),

            SubjectTextBox.Text, 

            DraftMessageCheckBox.Checked,

            ReadReceiptCheckBox.Checked)) 

        {

            email.Recipients.AddTo(ToTextBox.Text);

           email.Subject = SubjectTextBox.Text;

            email.BodyText = TextBodyTextBox.Text;

            email.Attachments.Add("Images\\peterpan.jpg");

 

            email.AddProperty(„BillingInformation“, "1234abcd");

  

            email.Save("c:\\temp\\email.msg");

                     }

        System.Diagnostics.Process.Start("c:\\temp\\email.msg");

 

 

so that my addin can work with this information, when this mail ist sent.

 



 

 

mit freundlichen Grüßen

Sighard Kohler

 

Von: Kees ***@***.***> 
Gesendet: Sonntag, 22. Oktober 2023 09:07
An: Sicos1977/MsgKit ***@***.***>
Cc: SigiKoh ***@***.***>; Author ***@***.***>
Betreff: Re: [Sicos1977/MsgKit] Creating a MSG - how to use AddProperty-method? (Issue #114)

 

What exactly do you want to do?

**Comment by Sicos1977** [comment]
I added the billing property. Please download the latest version from nuget.

You then can use it like this

![image](https://github.com/Sicos1977/MsgKit/assets/6692947/8f4ed9f2-5983-4fe9-aca5-22acd2d8bb91)

**Comment by SigiKoh** [comment]
wow – you made my day! 😊

thank you very much!!

 

 

Von: Kees ***@***.***> 
Gesendet: Montag, 23. Oktober 2023 07:35
An: Sicos1977/MsgKit ***@***.***>
Cc: SigiKoh ***@***.***>; Author ***@***.***>
Betreff: Re: [Sicos1977/MsgKit] Creating a MSG - how to use AddProperty-method? (Issue #114)

 

I added the billing property. Please download the latest version from nuget.

You then can use it like this

 <https://user-images.githubusercontent.com/6692947/277238319-8f4ed9f2-5983-4fe9-aca5-22acd2d8bb91.png>

**Comment by SigiKoh** [comment]
unfortunately it does not work properly yet:
After I added the property and saved the msg file, MFCMAPI shows an error.

![grafik](https://github.com/Sicos1977/MsgKit/assets/72381785/c4a90827-9823-4640-835b-a6f2dcbb421e)

When I display this msg-file in outlook, the property disappears:
![grafik](https://github.com/Sicos1977/MsgKit/assets/72381785/4953848f-b921-4948-b19a-067ff10f70c7)

**Comment by Sicos1977** [comment]
I guess it expects some kind of format in that property. Do you have an e-mail that has this property set so that I can look how this property is build up? When looking to the PidLidBilling property (https://learn.microsoft.com/en-us/office/client-developer/outlook/mapi/pidlidbilling-canonical-property) it expects an unicode string... but I have no idea what needs to be in this string.

**Comment by SigiKoh** [comment]
yes, here is a sample …

**Comment by SigiKoh** [comment]
hi,

do you think, there is any chance of a solution to my problem?

thank you!

**Comment by Sicos1977** [comment]
I'll try to look into it again. It was a very busy week last week so I did not do much on my opensource projects.

**Comment by Sicos1977** [comment]
I looked into your example e-mail and I think Outlook is probably expecting some other parameters to. But without any good documentation about how this works it is hard to figure out.

**Comment by Sicos1977** [comment]
This is all I can find online about that property

https://stackoverflow.com/questions/60117994/vb-net-microsoft-exchange-webservices-data-task-class-find-billinginformati

**Comment by SigiKoh** [comment]
hi,

for me, whole MAPI is quite complicated.

i asked this question in a forum an got an answer with „NamedProperty“, but this didnt help me …

https://stackoverflow.com/questions/77324103/creating-a-msg-using-msgkit-how-to-use-addproperty-method/77325551#77325551

?

**Comment by Sicos1977** [comment]
I just released a new nuget package. This one should work when trying to add a named property. I totally missed it that this was a named property not a normal one so the code I gave you never worked.... sorry about that... I just only now had the time to look into it a little bit deeper.

![image](https://github.com/Sicos1977/MsgKit/assets/6692947/b05be699-0474-44e9-9397-2e1cd179944a)

![image](https://github.com/Sicos1977/MsgKit/assets/6692947/0fb9c75c-ef6f-4bd8-8ac7-b951cddf5b22)

**Comment by SigiKoh** [comment]
Great!! Thank you! :-)

**Comment by Sicos1977** [comment]
Just to notice, it is normal that the property gets another value. This is how named properties work. 

Just let me know it this fixes your issue so that I can close this issue.

**Comment by SigiKoh** [comment]
i just tested – works! thumbs up…
