### ISSUE TITLE
Compatibility with .NET 5.0 or higher

### ISSUE THREAD

**Issue by Jovialus** [Sicos1977/MsgKit#117]
Hello there,

I was wondering if you will update MsgKit for compatiblity with .NET 5.0 or higher.

Thanks in advance!

Jelmer

**Comment by Sicos1977** [comment]
No :-) ... because it already is working on .net 5.0 and higher --> https://www.nuget.org/packages/MsgKit#supportedframeworks-body-tab

**Comment by Jovialus** [comment]
Hi there,

Thank you for the quick response. I am trying to use it in UiPath but I can't seem to use it anymore. Before it was working for me but it is now not showing up anymore. I figured it was because of the .net version.

Van: Kees ***@***.***>
Verzonden: dinsdag 16 januari 2024 16:06
Aan: Sicos1977/MsgKit ***@***.***>
CC: Holwerda, Jelmer ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Sicos1977/MsgKit] Compatibility with .NET 5.0 or higher (Issue #117)

U ontvangt niet vaak e-mail van ***@***.*** Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

No :-) ... because it already is working on .net 5.0 and higher --> https://www.nuget.org/packages/MsgKit#supportedframeworks-body-tab

-
