### ISSUE TITLE
Basic support of tasks

### ISSUE THREAD

**Issue by achimmm** [Sicos1977/MsgKit#122]
Hi,

I love your lib, but one thing I'm crucially missing is the creation of tasks. Is there some timeline when this functionality will be available?

**Comment by Sicos1977** [comment]
You are right... I see that I never finished that... did not realize that

`throw new NotImplementedException("This functionality is not yet completely implemented");`

I have to look how difficult it is to add this functionality and how much time this will cost me.

**Comment by achimmm** [comment]
Hi Kees,

works perfect for me. A Great thank you!

Lg Achim

Am 12.03.2024 um 13:54 schrieb Kees ***@***.***>:

﻿

I added code to make a task, just get the latest code from GitHub and try it out to see if it fits your needs.

If it works and I have polished to code here and there than I'll release a new nuget package

**Comment by Sicos1977** [comment]
Just released a new nuget package

**Comment by achimmm** [comment]
Sorry to bother you again- BodyHtml doesn‘t seam to work…

Am 14.03.2024 um 19:27 schrieb Kees ***@***.***>:

﻿

Just released a new nuget package
