### ISSUE TITLE
Can you make a MsgKitLite based on MimeKitLite?

### ISSUE THREAD

**Issue by gmarbury** [Sicos1977/MsgKit#124]
Whenever I add MsgKit to my project it pulls in all the crypto stuff that I'm not wanting anyway. This also seems to mess up the .Net Native Compiler for UWP. I know Xamarin is going away ( basically dead) but being able to save MSG files based on MimeKitLite would be cool, and maybe even bring in MailKitLite so you can send them. As an alternative, can you give me quick c# function that only requires a reference to OpenMcdf and MimeKitLite to save a MsgFile given a complete MimeMessage ?

**Comment by Sicos1977** [comment]
Sure I can look into it... I did not even know there was a MimeKit lite :-)

**Comment by gmarbury** [comment]
I pulled the code down and saved a copy of MsgKit.csproj as MsgKitLite.csproj in the same folder changing only the nuget reference from MimeKit to MimeKitLite and everything just compiled as is.
