### ISSUE TITLE
Can't send draft email via Outlook New

### ISSUE THREAD

**Issue by dexxtr** [Sicos1977/MsgKit#125]
I have the code below to create *.msg file and then open it for further sending. MsgKit v2.8.0

> using (var email = new MsgKit.Email(new MsgKit.Sender("", string.Empty), _subject, true))
{
    email.Recipients.AddTo("john@doe.com")
    email.Subject = _subject;
    email.BodyText = _bodycontent;
    email.Importance = MsgKit.Enums.MessageImportance.IMPORTANCE_NORMAL;
    email.IconIndex = MsgKit.Enums.MessageIconIndex.NewMail;
    email.Attachments.Add(_sharedFilePath);
    email.Save(_msgFilePath);
}

The file has been generated well. When I open it in Outlook New v1.2024.424.300 and Client Version is 202440419007.27 and trying to send the Outlook shows me the error message
`This message can't be sent right now. Please try again later.`

At the same time, sending this *.msg file via Outlook Old works absolutely well. Do I need to change some settings or is it Outlook New issue?

**Comment by Sicos1977** [comment]
I have no idea why you get this error in the new Outlook client. Without a more detailed error it is hard for me to guess why you are getting this error.

**Comment by dexxtr** [comment]
I also can't get any details from Outlook client :( Or maybe somewhere in the system logs?

**Comment by SharePointPro** [comment]
Same issue here.
