### ISSUE TITLE
Embedded images don't seem to appear when viewed in Outlook

### ISSUE THREAD

**Issue by krugertech** [Sicos1977/MsgKit#128]
Hi There. Thanks for this great library. 

When I create a new email and embed/inline an image, the image does not seem to appear when viewing the .msg file in Outlook. 

![image](https://github.com/Sicos1977/MsgKit/assets/28920021/5af17422-3398-4bd3-bc05-ec4df59edf18)

OutlookSpy can detect the image attachment though. 

![image](https://github.com/Sicos1977/MsgKit/assets/28920021/1eac959b-87f5-453e-b04a-99a0ce81fbec)

Here is the code I used. I tested different .jpg files and tried setting different rendering positions in an effort to get the embedded image to display in Outlook without success. 

```
    static void TestInlinedAttachment()
    {
        using (var email = new Email(
                new Sender("peterpan@neverland.com", "Peter Pan"),
                new Representing("tinkerbell@neverland.com", "Tinkerbell"),
                "Hello Neverland subject"))
        {
            email.Recipients.AddTo("captainhook@neverland.com", "Captain Hook");
            email.Recipients.AddCc("crocodile@neverland.com", "The evil ticking crocodile");
            email.Subject = "This is the subject";
            email.BodyText = "Hello Neverland text";
            email.BodyHtml = "<html><head></head><body><b>Hello Neverland html</b></body></html>";
            email.Importance = MsgKit.Enums.MessageImportance.IMPORTANCE_HIGH;
            email.IconIndex = MessageIconIndex.ReadMail;
            email.Attachments.Add(File.OpenRead(@"D:\IMG-20240524-WA0000.jpg"),"img.jpg", -1, isInline: true, "img.jpg");
            email.Save(@"d:\email.msg");
        }
    }
```

**Comment by Sicos1977** [comment]
This is not how you embed inline images. You need to add an image tag into you html and set the image source to cid:<the id you have given your inline image>

**Comment by Sicos1977** [comment]
```html
<html>
   <head>
      <title>Peter Pann</title>
   </head>
   <body>
      <b>Hello Neverland html</b><br/>
     <img src="cid:tinkerbell.jpg">
   </body>
</html>
```
