### ISSUE TITLE
Error is Subject of the Email is less than 5 characters

### ISSUE THREAD

**Issue by Timothyoverton** [Sicos1977/MsgKit#13]
Subject of the email is: `7.59`
When creating the email object, I'm getting this error:
`-		$exception	{"startIndex cannot be larger than length of string.\r\nParameter name: startIndex"}	System.ArgumentOutOfRangeException
`

this stacktrace:
`
		StackTrace	"   at System.String.Substring(Int32 startIndex, Int32 length)\r\n   at MsgKit.Email.SetSubject() in C:\\Users\\Kees\\Documents\\GitHub\\MsgKit\\MsgKit\\Email.cs:line 236\r\n   at MsgKit.Email..ctor(Sender sender, Representing representing, String subject) in C:\\Users\\Kees\\Documents\\GitHub\\MsgKit\\MsgKit\\Email.cs:line 208\r\n   at CreateMSG.Program.Main(String[] args) in V:\\Testing\\CSharpCreateMSG\\CreateMSG\\Program.cs:line 25"	string
`

code:
```
var email = new Email(
                new Sender("peterpan@neverland.com", "Peter Pan"),
                new Representing("tinkerbell@neverland.com", "Tinkerbell"),
                "7.59");
               // "Hello Neverland subject");
```

**Comment by Timothyoverton** [comment]
subject "abcd" fails
subject "abcde" is ok
having 5 spaces is ok as well

**Comment by Sicos1977** [comment]
Are you sure that you are using the latest version? There was an error with the subject in a previous version but that has been resolved some time ago.

![image](https://user-images.githubusercontent.com/6692947/28403056-3ae0ec88-6d23-11e7-9b52-c0687e720f40.png)

**Comment by Timothyoverton** [comment]
Hi Kees, I have to run version 1.0.0, the latest version won't run for me: https://github.com/Sicos1977/MsgKit/issues/12

**Comment by Timothyoverton** [comment]
Version 1.1.4 is working with any length subject - thanks Kees
