### ISSUE TITLE
Edit existing msg files?

### ISSUE THREAD

**Issue by akamor** [Sicos1977/MsgKit#130]
Hello,

Thanks for your great projects, MsgReader and MsgKit both!

I have a collection of .msg files (saved emails from outlook) and I'd like to make edits to these messages. Is it possible to open a .msg file for editing, make edits, then save it?  From what I can tell, today MsgKit just supports creating emails from scratch.

**Comment by Sicos1977** [comment]
No that is not possible, you could use my other project MSGReader to read an msg file and than construct a new one with MsgKit... the planning is to merge msgreader into msgkit but you know how that goes when you have to do it in your own free time :-) ... 10 year plan :-)
