### ISSUE TITLE
Outlook 365 cannot send msg file created with MsgKit

### ISSUE THREAD

**Issue by ngarcia70** [Sicos1977/MsgKit#138]
Is the current or future version support Outlook 365? The msg file created won't send in new outlook. No specific error, just "There was a problem sending this message. Try sending it again or close this draft and send it later." Any way to resolve this from MsgKit side?

**Comment by Sicos1977** [comment]
I also use Outlook 365 and I have no problems sending msg files. Did you try to generate the msg file in draft mode?

**Comment by SharePointPro** [comment]
I'm having this same issue with new Outlook. 
Classic outlook works fine with these MSG files.
