### ISSUE TITLE
HTMLBody not shown in Outlook Message when parameter draft is set to true

### ISSUE THREAD

**Issue by Starrscream** [Sicos1977/MsgKit#14]
When I use to optional draft parameter of the Email Class, the HTML-String assigned to the BodyHtml-Property is not displayed in the saved Msg-File. If I set the draft parameter to false the HTML-Body is displayed, but Msg-File is in Read-Only-Mode.

**Comment by Sicos1977** [comment]
I just modified the MsgKit test application to create a draft message. When I create the MSG file I don't have any problems in changing the text and the body is also visible.

![image](https://user-images.githubusercontent.com/6692947/29576110-f8215fd2-8766-11e7-81fd-083f1d215e4f.png)

**Comment by Sicos1977** [comment]
Ow wait... now I see it. The text is displayed instead of the HTML

**Comment by Sicos1977** [comment]
I check the Microsoft documentation and this seems to be normal behavior when the message does not contain the property PR_RTF_COMPRESSED tag.... which it doesn't

**Comment by Starrscream** [comment]
Thank you for checking the issue.

MsgKit is a great application. Thank you for that too.

Best regards,
Tom

**Comment by Sicos1977** [comment]
Your welcome

**Comment by joaonoch** [comment]
So how to add the PR_RTF_COMPRESSED tag (or is that not possible)?

**Comment by Sicos1977** [comment]
I found a highly experimental workaround to support HTML embedded into RTF when the Email is set to draft. See this commit --> 081e138

Just try it out an let me know if it works for you.
