### ISSUE TITLE
Unable to attach .msg file

### ISSUE THREAD

**Issue by sailendramanoj** [Sicos1977/MsgKit#24]
public static void SaveEmailWithAttachments(string subject, string body,string emailFileName, string filesLocation, string sharedPath,List<string> selectedFileList)
        {
            /*
            MailMessage mail = new MailMessage();
            mail.Body = body;
            mail.To.Add(new MailAddress(""));
            mail.From = new MailAddress("");
            mail.Subject = subject;

            string[] fileEntries = Directory.GetFiles(filesLocation);
            foreach (string fileName in fileEntries)
            {
                if (File.Exists(fileName))
                {
                    //if (selectedFileList.Any(a => a == fileName))
                    //{
                    Attachment attachment = new Attachment(fileName, MediaTypeNames.Application.Octet);
                    ContentDisposition disposition = attachment.ContentDisposition;
                    disposition.CreationDate = File.GetCreationTime(fileName);
                    disposition.DispositionType = DispositionTypeNames.Attachment;
                    mail.Attachments.Add(attachment);
                    //}
                }
            }
            try
            {

                string emailFile = Path.Combine(filesLocation, emailFileName);
                string emailFileWithEML = Path.ChangeExtension(emailFile, ".EML");

                mail.Save(emailFileWithEML);

                Independentsoft.Email.Mime.Message mimeMessage = new Independentsoft.Email.Mime.Message(emailFileWithEML);

                Independentsoft.Msg.Message msgMessage = new Independentsoft.Msg.Message(mimeMessage);

                msgMessage.Save(sharedPath);

                if (File.Exists(emailFileWithEML))
                {
                    File.Delete(emailFileWithEML);
                }
            }
            catch (Exception)
            {

            }
            */
            try
            {

                using (var email = new Email(
                    new Sender("", ""), subject,true))
                {
                    //email.Recipients.AddTo("", "");
                    //email.Recipients.AddCc(" ", "");
                    email.Subject = subject;
                   // email.BodyText = "Hello Neverland text";
                    email.BodyHtml = body;
                    //email.Importance = MessageImportance.IMPORTANCE_HIGH;
                    email.IconIndex = MessageIconIndex.UnsentMail;
                    string[] fileEntries = Directory.GetFiles(filesLocation);
                    foreach (string fileName in fileEntries)
                    {
                        if (File.Exists(fileName))
                        {
                          
                            email.Attachments.Add(fileName);
                            //Stream fs = File.OpenRead(fileName);
                           // email.Attachments.Add(fs,fileName);
                        }
                    } 
                    email.Save(sharedPath);

                    // Show the E-mail
                }
            }
            catch (Exception e)
            {
                Log.Error("Error: " + e.Message, e);
            }
        }

**Comment by Sicos1977** [comment]
What is exactly your problem? Because I see that you are using a commercial library and MSGKit together?

**Comment by Anjibabu** [comment]
I am also facing  issue while opening .msg file in the attachment

**Comment by Sicos1977** [comment]
Please see my first post, what is exactly the problem. Without an exception, stacktrace or image I don't know how to help you.

**Comment by sailendramanoj** [comment]
While opening I am  getting an error " one or more parameter incorrect "
