### ISSUE TITLE
I am able attach the .msg file but  facing issue while opening .msg file in the attachment

### ISSUE THREAD

**Issue by Anjibabu** [Sicos1977/MsgKit#25]

**Comment by Anjibabu** [comment]
using (var email = new Email(
                new Sender("", ""), subject,true))
            {
                //email.Recipients.AddTo("", "");
                //email.Recipients.AddCc(" ", "");
                email.Subject = subject;
               // email.BodyText = "Hello Neverland text";
                email.BodyHtml = body;
                email.IconIndex = MessageIconIndex.UnsentMail;
                string[] fileEntries = Directory.GetFiles(filesLocation);
                foreach (string fileName in fileEntries)
                {
                        email.Attachments.Add(filePath)
                    }
                } 
                email.Save(savedPath);

**Comment by Anjibabu** [comment]
Please help on this ASAP

**Comment by Anjibabu** [comment]
While opening I getting error " one or more parameter incorrect  "

**Comment by Sicos1977** [comment]
Ok I see what the problem is. I fixed it in this commit https://github.com/Sicos1977/MsgKit/commit/58b3642b56ff9019e17d856c58b76d9b69c0dd94. Just get the latest version from GitHub, compile it and you should be fine.
