### ISSUE TITLE
Msg file as attachments

### ISSUE THREAD

**Issue by androidrafbran** [Sicos1977/MsgKit#26]
Hello,
very useful library. However, I am having a problem. If I try to save an email that has an .msg file as attachment, the attachment doesn't open. It says "resource is busy or you lack sufficient access rights or permissions". Do you know how to fix this?

Thanks

**Comment by Sicos1977** [comment]
Can you send me the file that is giving you this error? Please zip the msg file before sending it to sicos2002@hotmail.com

**Comment by androidrafbran** [comment]
I sent you an example of a file with the problem.
The problem is that the library sets the attachment type to ATTACH_EMBEDDED_MSG, giving me the error.
I tried to send it by changing the extension, so that the type changes to ATTACH_BY_VALUE. This way, if I save the attachment and rename it back to .msg extension I can open it.
The AttachmentType property is read only, a possible solution is to make it settable so its possible to change it.

**Comment by Sicos1977** [comment]
It seems that I already fixed this issue in this commit --> https://github.com/Sicos1977/MsgKit/commit/58b3642b56ff9019e17d856c58b76d9b69c0dd94

But I probably never released a new nuget package with that fix in it. Just grab the source from GitHub and compile it and you should be fine.

**Comment by androidrafbran** [comment]
Thank you. It works now. But I adopted another solution. I used your MsgReader library to parse the msg file and forward it other than attach it. Better solution for me. 
However I opened an issue for that library. I’m not able to use it by parsing a MemoryStream. Can you help me?

Thank you
