### ISSUE TITLE
"EX" type addresses are not properly looked up in an Exchange environment

### ISSUE THREAD

**Issue by Sharpiro** [Sicos1977/MsgKit#29]
**Overview**
I am trying to add sender/recipient information as "EX" addresses, but when I verify in Outlook, the created MSG files are unable to resolve to the address in AD, and I know 100% that the EX addresses are valid, and they resolve when using MSGs created from the Outlook Interop library.

**Code**
```
const string address = "/o=Company/ou=Exchange Group (XYBZHF23456LT)/cn=Recipients/cn=User Name";
var sender = new Sender(address, "Display, Name", MsgKit.Enums.AddressType.Ex, canLookupEmailAddress: true);
var subject = "Hello Neverland subject";
using (var email = new Email(sender, subject))
{
    email.Recipients.AddTo("/o=Company/ou=Exchange Group (XYBZHF23456LT)/cn=Recipients/cn=User Name", "Display, Name", MsgKit.Enums.AddressType.Ex);
    email.Save(@"C:\temp\email.msg");
}

// using MSGReader
using (var msg = new Storage.Message(@"C:\temp\email.msg"))
{
    var email = msg.Sender.Email; //this is an empty string
    var recipient = msg.Recipients.Single(); // this data appears* to be valid
}
```

**Explanation**
It seems to me that the MsgKit library is incorrectly writing sender and recipient data when it is in an "EX" format, causing it to be unable to be resolved when opened in Outlook.  When analyzing the data with your MSGReader library, when in "EX" format, the email address always shows as an empty string, which may be an issue w/ MSGReader library, b/c in Outlook the "EX" address does show, but just doesn't resolve to the given user, and simply displays in the following format in the sender area of Outlook:
```Display, Name </o=Company/ou=Exchange Group (XYBZHF23456LT)/cn=Recipients/cn=User Name>```

The recipient information appears to be valid from the MSGReader library, but the "EX" addresses still fail to do a lookup when opened in Outlook.

**Notes**
- The lookup fails regardless of "canLookupEmailAddress" being set
- Lookup fails regardless of "AddressType" being supplied

**Comment by Sicos1977** [comment]
Can you send me a msg file that is made in Outlook with the EX property that is correctly doing a lookup and also a msg file that you made with MsgKit. I then can try to figure out which properties are missing to make this work. Please put both msg files in a zip file before sending it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
I got your message but there are a lot of properties in there.

![image](https://user-images.githubusercontent.com/6692947/35874030-b5da5316-0b6b-11e8-9eeb-0ed687ca62b0.png)

**Comment by Sharpiro** [comment]
Thanks for looking into this.

I looked into it a bit, and apparently when the outlook interop library/Outlook creates a MSG file, it first resolves to AD.  So I think my solution would be to go to AD myself to resolve the SMTP address, or at some point build it into the MsgKit library where if an EX address is detected, instead of writing it as an invalid email address, it would do the lookup on its own.

**Comment by Sicos1977** [comment]
I'm closing this issue since the lookup is an Outlook thing and MsgKit is just to make MSG files, not to lookup information in an Active Directory.

**Comment by Sharpiro** [comment]
Sounds good.

I do have a quick question. In your comment [above](https://github.com/Sicos1977/MsgKit/issues/29#issuecomment-363500226), what tool is it that you are using to view all those properties in the screenshot?
