### ISSUE TITLE
File already used by another process

### ISSUE THREAD

**Issue by mwolfaardt** [Sicos1977/MsgKit#3]
Create a msg file with attachments, save the file and try to recreate the file again. I keep on receiving the file is being used by another process error.

**Comment by Sicos1977** [comment]
Did you use the example on the main github page from this repository?

**Comment by mwolfaardt** [comment]
Yes, I used the example provided

**Comment by Sicos1977** [comment]
You are sure that you closed the opened message?

Because the line below opens the message en then Windows locks it :)

// Show the message
System.Diagnostics.Process.Start(@"c:\test.msg");

**Comment by mwolfaardt** [comment]
I didn't open the msg file after i saved it

**Comment by Sicos1977** [comment]
I tried but can't seem to reproduce your problem. Try to dispose the email object before you open the e-mail and look if that fixes your problem.

`            using (var email = new Email(
                new Sender("peterpan@neverland.com", "Peter Pan"),
                new Representing("tinkerbell@neverland.com", "Tinkerbell"),
                "Hello Neverland subject"))
            {

                email.Recipients.AddTo("captainhook@neverland.com", "Captain Hook");
                email.Recipients.AddCc("crocodile@neverland.com", "The evil ticking crocodile");
                email.Subject = "This is the subject";
                email.BodyText = "Hello Neverland text";
                email.BodyHtml = "<html><head></head><body><b>Hello Neverland html</b></body></html>";
                email.Importance = MessageImportance.IMPORTANCE_HIGH;
                email.IconIndex = MessageIconIndex.UnsentMail;
                email.Attachments.Add("Images\\peterpan.jpg");
                email.Attachments.Add("Images\\tinkerbell.jpg");
                email.Save("test.msg");
            }
            System.Diagnostics.Process.Start("test.msg");`

**Comment by Timothyoverton** [comment]
This is linked to the same problem I was having, hope you can replicate it by trying to delete/move 1 of the attachments after saving the msg, after the Email object is disposed...

**Comment by lorant-csonka-planorama** [comment]
This issue is still present.
