### ISSUE TITLE
Error saving an e-mail

### ISSUE THREAD

**Issue by antoniogarcez** [Sicos1977/MsgKit#30]
Hi,

I am trying to create an e-mail file (.msg) but always gives the same error.

Code:
```
using (MsgKit.Email email = new MsgKit.Email(new MsgKit.Sender(authUser.Email, authUser.Name), string.Empty))
{
       email.BodyHtml = GenerateInlineHTML(key, srcCode, Server);
       //email.Save(stream);

       //byte[] teste = ObjectToByteArray((object)email);

       switch (key)
        {
                case "SPECIALS":
                        path = VariablesRep.CODE_SPECIALS_FOLDER_W + @"E-mails\";
                        break;
         }

         email.Save(path + emailFileName);

         //emailFile.Add("e-mail", JObject.FromObject(new MultipartFile(new MemoryStream(teste), "e-mail", emailFileName)));
}
```

And, this is the error:

> [ArgumentNullException: String reference not set to a string instance.
Parameter name: s]
   System.Text.Encoding.GetBytes(String s) +12586649
   MsgKit.Helpers.Strings.WriteNullTerminatedUnicodeString(BinaryWriter binaryWriter, String str) in C:\Users\AO303388\source\repos\MsgKit\MsgKit\Helpers\Strings.cs:134
   MsgKit.Structures.OneOffEntryId.ToByteArray() in C:\Users\AO303388\source\repos\MsgKit\MsgKit\Structures\OneOffEntryId.cs:172
   MsgKit.Sender.WriteProperties(TopLevelProperties propertiesStream) in C:\Users\AO303388\source\repos\MsgKit\MsgKit\Sender.cs:111
   MsgKit.Email.WriteToStorage() in C:\Users\AO303388\source\repos\MsgKit\MsgKit\Email.cs:369
   MsgKit.Email.Save(String fileName) in C:\Users\AO303388\source\repos\MsgKit\MsgKit\Email.cs:486
   FAMO.CODE.Controllers.<ExportContentToEmail>d__3.MoveNext() in L:\TFS\DOTNET\Development\FAMO.CODE\FAMO.CODE\Controllers\GlobalController.cs:91
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +97
   System.Web.Mvc.Async.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult) +17
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__11_0() +50
   System.Web.Mvc.Async.<>c__DisplayClass11_1.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2() +228
   System.Web.Mvc.Async.<>c__DisplayClass7_0.<BeginInvokeActionMethodWithFilters>b__1(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass3_6.<BeginInvokeAction>b__3() +35
   System.Web.Mvc.Async.<>c__DisplayClass3_1.<BeginInvokeAction>b__5(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState) +11
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +45
   System.Web.Mvc.<>c.<BeginExecute>b__151_2(IAsyncResult asyncResult, Controller controller) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState) +28
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +577
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +163

**Comment by Sicos1977** [comment]
This works fine overhere

```csharp
            using (MsgKit.Email email = new MsgKit.Email(new MsgKit.Sender("someone@somewhere.com", "Mister nobody"), string.Empty))
            {
                email.BodyHtml = "<html><head></head><body>Hello world</body></html>";
                email.Save("d:\\test.msg");

                //emailFile.Add("e-mail", JObject.FromObject(new MultipartFile(new MemoryStream(teste), "e-mail", emailFileName)));
            }
```

**Comment by Sicos1977** [comment]
It seems that your authUser.Email is returning a null and that generates the error.

**Comment by Sicos1977** [comment]
I added a null check to prevent your error from happening. See this commit a3814a546c04919dc7fadba9c901a31933ca0d41

**Comment by antoniogarcez** [comment]
Thank you :D
