### ISSUE TITLE
No sender

### ISSUE THREAD

**Issue by johnwc** [Sicos1977/MsgKit#33]
Is it possible to create a item with no sender set? When creating a draft, I'd like to have no sender and let Outlook set this when they actually send the email.

**Comment by Sicos1977** [comment]
Yes that should be possible, but for that to work I need to make some changes to MSGKit because I designed the code in such way that it always want to have a sender.

**Comment by Sicos1977** [comment]
What you also can do is just set sender to null like this.
```

using (var email = new Email(
    null,
    SubjectTextBox.Text, DraftMessageCheckBox.Checked))
{
    //email.Recipients.AddTo(ToTextBox.Text);
    email.Recipients.AddCc(CcTextBox.Text);
    email.Recipients.AddBcc(BccTextBox.Text);
    email.Subject = SubjectTextBox.Text;
    email.BodyText = TextBodyTextBox.Text;
    email.BodyHtml = HtmlBodyTextBox.Text;
    email.SentOn = SentOnDatePicker.Value.ToUniversalTime();
```
