### ISSUE TITLE
Adding inline embedded images shows as attachments

### ISSUE THREAD

**Issue by johnwc** [Sicos1977/MsgKit#35]
When creating a email in outlook with embedded images, the images never show as attachments to the email, to the recipient or in my sent folder.

When I create a draft email with MsgKit and save it, then open with outlook; the embedded images don't show as attachments. But, when I send the email, the images show up as attached files to the recipient and also the same in my sent folder.

**Comment by Sicos1977** [comment]
I can reproduce the problem over here, I'll have to figure out why this is not working. I'll let you know when it is fixed.

**Comment by Sicos1977** [comment]
The bug is fixes. Please get the latest source code from GitHub and try if out. When everything seems to work as intended I will release a new NuGet package.

**Comment by johnwc** [comment]
I pull it from nuget, can you publish a pre-release to test with?

**Comment by johnwc** [comment]
Something that I've also noticed. The icon shows as draft icon on sent emails to recipients.

**Comment by Sicos1977** [comment]
I just published a new package to NuGet (version 1.2.6).

You can install it with this command `Install-Package MsgKit -Version 1.2.5`

**Comment by Sicos1977** [comment]
Can you please confirm that it is fixed?

**Comment by johnwc** [comment]
It seems to be fixed now.

Just a FYI, I have created PowerShell cmdlets to expose the ability to create and save Outlook MSG files. The GitHub for it is [here](https://github.com/Simpler-Software/SS.PowerShell), and the PowerShell gallery is [here](https://www.powershellgallery.com/packages/SS.PowerShell/). With this in PowerShell we can now automate tasks that needs to create draft emails to be sent.
