### ISSUE TITLE
Possibility to add email headers

### ISSUE THREAD

**Issue by bouskdav** [Sicos1977/MsgKit#36]
Hi,

could you please add a feature to add a KeyValuePairs to MSG headers as one is able to do so with System.Net.Mail.MailMessage?
Currently I'm trying to add X-Unsent=1 header - with no success.

Thanks and cheers,
David

**Comment by Sicos1977** [comment]
Sure, I'll look into it this weekend.

**Comment by Sicos1977** [comment]
One week to late but.... I added an option to set custom header values.

```
var email = new Email();
email.TransportMessageHeaders = new MessageHeader();
// ... do something with it, for example
email.TransportMessageHeaders.SetHeaderValue("X-MY-CUSTOM-HEADER", "EXAMPLE VALUE");
```
Please let me know if this works for you, I'll then release a new NuGet package.

**Comment by Sicos1977** [comment]
No response... closed

**Comment by bouskdav** [comment]
Sorry for late reply! Thanks a lot man. Works like a charm 👍

**Comment by Sicos1977** [comment]
Your welcome
