### ISSUE TITLE
How to add embedded messages as an attachment using stream

### ISSUE THREAD

**Issue by rsrini83** [Sicos1977/MsgKit#39]
Hi,

I'm trying to add attachments, however, i would like to understand how can I add the embedded attachment using stream object. Please provide or point me any example

Thanks in advance.

--Srinu

**Comment by Sicos1977** [comment]
![image](https://user-images.githubusercontent.com/6692947/46002462-69ff9480-c0ae-11e8-839b-8df66063e134.png)
