### ISSUE TITLE
How to add other properties ?

### ISSUE THREAD

**Issue by rsrini83** [Sicos1977/MsgKit#41]
Hi,

I have other attributes(PidTag****) which I want to add to the mail item. Is it possible to add these custom attributes ?  

--Srinu

**Comment by Sicos1977** [comment]
No there is no option implemented to do that. What property/properties do you want to add for what reason?

**Comment by rsrini83** [comment]
Hi,

We are extracting attributes from EWS export item format (FastTransferStream). we are able to extract all the attributes, but we would like to export these into Msg format. So we are looking for the provision to add using this framework. Any guidance on how to add these?

**Comment by Sicos1977** [comment]
I need to add a method to give that possibility. It's not that hard to do that. I'll see if I can make some time this weekend. Can you give me a list with some properties (and values) that you want to add so that I have some test cases?

**Comment by rsrini83** [comment]
Thanks for the API. Will take the changes and will confirm after verification.

**Comment by Sicos1977** [comment]
And?

**Comment by rsrini83** [comment]
Hi,

My apologies for later reply.  I was down with fever for two weeks, so i couldn't verify your changes. Current changes seem to be okay. However, I will not be able to create PropertyTag outside the assembly. As PropertyTag is the internal constructor.  I think this also needs to be made it as public, then i'm able to create the property tags and proceed as i want it. 

--Srinu
