### ISSUE TITLE
 Could not load file or assembly 'OpenMcdf, Version=2.1.6.28924

### ISSUE THREAD

**Issue by yoshatest** [Sicos1977/MsgKit#42]
Hi,
Just a minor issue:
The above error occurs on a slightly messy solutions/projects. The solution contains a few projects and is basically on ASP Core 2.1 but targeting full .net 472. One of the projects cosumes MsgKit installed through Nuget, it also targets 472. 

After updated to MsgKit 1.2.7, the error message saying version conflict has disappeared (thanks!) but now it causes exception saying the subject at runtime. If I go Nuget again and down-grade the OpenMcdf to Version 2.1.6.28924, it works fine, i.e. no exceptions. The solution does not use OpenMcdf directly but only through MsgKit. 

Cheers,

**Comment by Sicos1977** [comment]
Can you please paste a screenshot with the exception? It's easier for me that way to figure out what is causing it.

**Comment by yoshatest** [comment]
Hi,
Thanks for looking after this. I tried to reproduce the issue in this afternoon without success. Sorry - it should have been my bad, there's no exceptions.  I just did (on Nuget GUI):
1. uninstalled MsgKit
2. uninstalled OpenMcdf
3. confirmed both no longer exist on Nuget packages, restarted VS2017

4. installed MsgKit 1.2.7 freshly.
5. confirmed that OpenMcdf  2.1.6.28924 was installed accordingly.

at 5), the latest OpenMcdf was somehow installed yesterday and that caused exceptions at runtime but it was likely my bad somewhere. There is no exception anymore, thanks, please close this.

One thing though, there is still a warning when build:
1>------ Rebuild All started: Project: Biz.ExJob, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3277: Found conflicts between different versions of "OpenMcdf" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

Cheers,
