### ISSUE TITLE
How to parse .Msg File Stream to Individual properties

### ISSUE THREAD

**Issue by kamalbabu** [Sicos1977/MsgKit#43]
@Sicos1977 Is it possible to parse a stream back to its initial properties?

i have my contents of a Msg File as byte array . Could you share a sample piece of code on how to achieve it?

Thanks

**Comment by Sicos1977** [comment]
How do you mean? MsgKit is a dll to create msg files not to read them. For that you need my other project MsgReader. That one will read an msg file and parse the properties
