### ISSUE TITLE
MsgKit.Exceptions.MKAttachmentExists: "The attachment with the name already exists"

### ISSUE THREAD

**Issue by madrianr** [Sicos1977/MsgKit#44]
Hello,

If I add Attachements with the following code and the name of the Attachement already exists I get an error:
MsgKit.Exceptions.MKAttachmentExists: "The attachment with the name 'Karpathos.msg' already exists"

here my code:
email.Attachments.Add(dokument.Dokumentinhalt.ToMemoryStream(), fileName);

what's the best way to avoid this error?

robert

**Comment by madrianr** [comment]
![unbenannt](https://user-images.githubusercontent.com/10518186/48701318-7c013d80-ebee-11e8-97bc-7345326359fc.JPG)

**Comment by Sicos1977** [comment]
Just check if an attachment with the same name already exists and if so add a _ or number add the end

**Comment by tbgrewal** [comment]
My email does not have any attachments but there are 2 png images with the same name in it and MsgKit reacts with an error complaining the name already exists. How can I take care of this by re-naming> Thanks.
