### ISSUE TITLE
Wrong header

### ISSUE THREAD

**Issue by mefihl** [Sicos1977/MsgKit#45]
Where convert msg to eml with mailconverter.exe i'am have this error:
![image](https://user-images.githubusercontent.com/5302754/48726911-05396400-ec31-11e8-88b3-ed6919fd878c.png)
Another error is when copy msg to outlook folder. 
After open msg with outlook and resave in outlook works ok.

**Comment by Sicos1977** [comment]
Are you sure that you are using MSGKit... because I see the Rebex.OutlookMessages namespace? I think you did put you issue in the wrong project :-)

**Comment by mefihl** [comment]
I'am create msg with MsgKit and try convert this file to eml with mailconverter.exe. Then i have error. Msg save from Outlook is convery without error.

**Comment by mefihl** [comment]
https://labs.rebex.net/mail-converter (Mail Converter), this error is show also when copy msg file create with MsgKit to outlook folder. Msg no copy in row but attachment to new email.
