### ISSUE TITLE
Add custom property

### ISSUE THREAD

**Issue by sanazyavari** [Sicos1977/MsgKit#46]
Hi - I am trying to add a custom property to an email. the property value is a string and holds information. I need to use the info in an outlook add-ons after sending the email to store it in a database . I went through all propertytags to see which one I can use. but I couldn't find any that is specific to custom property (user define field). I want to create a new propertytag but then I can not set name and value. I used the code below, but I could n't open the mail after adding them.
 // Add a custom property
                    email.AddProperty(PropertyTags.PR_AUTO_FORWARDED, true);
                    email.AddProperty(PropertyTags.PR_AUTO_FORWARD_COMMENT_W, "entrytype,entryID,xxx");

I appreciate if you get back to me.
Thanks,
Sanaz

**Comment by Sicos1977** [comment]
If you want to add a custom property then you have to use "named properties" and this is something that is currently not supported. I'll add it on my todo list but can't make any promises when it is implemented.
