### ISSUE TITLE
disappearing attachment since 2.1.0

### ISSUE THREAD

**Issue by thomaslok81** [Sicos1977/MsgKit#47]
Below code works in version 1.2.4 but NOT in 2.1.0. Any idea why?

 email.Attachments.Add(fileStream, ReplaceInvalidCharachtersInString(name), -1, true,
                            attachment.GetAttributeValue<string>(AttachmentStatics.FileName));

**Comment by Sicos1977** [comment]
No idea, I'll have to look into this
