### ISSUE TITLE
Its not displaying the Inserted picture in the body

### ISSUE THREAD

**Issue by dpakgithub82** [Sicos1977/MsgKit#48]
my email message body has the picture in it,when save iand open the *.msg file ,the inserted picture is not getting displayed.

**Comment by Sicos1977** [comment]
Did you set a content id on the picture with cid:<something> and did you put that id in the attachment?

**Comment by dpakgithub82** [comment]
Yes I did,Can you please tell me with example(sample code) ,that would be great.

**Comment by Sicos1977** [comment]
Just get the code from GitHub it has a MsgKitTesttool that shows how to embed a picture in an e-mail.

**Comment by dpakgithub82** [comment]
using (var email = new Email(new Sender(sharePointFile.From, "deepak"), sharePointFile.Subject))
                {
                    email.Recipients.AddTo(sharePointFile.To);
                    email.Recipients.AddCc(sharePointFile.Bcc);
                    email.Subject = sharePointFile.Subject;
                    email.BodyText = sharePointFile.BodyText;
                    email.BodyHtml = sharePointFile.BodyHtml;
                    email.Importance = MessageImportance.IMPORTANCE_HIGH;
                    email.IconIndex = MessageIconIndex.ReadMail;
                    for (int i = 0; i <= sharePointFile.filecontent.Count - 1; i++)
                    {
                        byte[] bytes = Convert.FromBase64String(sharePointFile.filecontent[i]["ContentBytes"].Value);
                        string pastedFileName = sharePointFile.filecontent[i]["Name"].Value;
                        //byte[] data = Convert.FromBase64String(sharePointFile.filecontent[i]["Id"].Value);
                        //string decodedString = Encoding.UTF8.GetString(data);
                        List<string> imgTag = GetImagesInHTMLString(sharePointFile.BodyHtml);
                        string contentId = GetContentId(imgTag.FirstOrDefault());
                        //if (string.IsNullOrEmpty(imgTag.Where(x => x.Contains(spfolder)).FirstOrDefault()) || !spfolder.Contains("pastedImage"))
                        //{
                        if (!pastedFileName.ToLower().Contains("pastedImage".ToLower()))
                        {
                            Stream stream = new MemoryStream(bytes);
                            object[] array1 = new object[9];
                            array1[0] = stream;
                            array1[1] = sharePointFile.filecontent[i]["Name"].Value;
                            array1[2] = DateTime.Now;
                            array1[3] = DateTime.Now;
                            array1[4] = AttachmentType.ATTACH_BY_VALUE;
                            array1[5] = 1;
                            array1[6] = false;
                            array1[7] = sharePointFile.filecontent[i]["Name"].Value;
                            array1[8] = false;
                            var ctor = typeof(MsgKit.Attachment).GetConstructors(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance).First();
                            var instance = ctor.Invoke(array1) as MsgKit.Attachment;
                            email.Attachments.Add(instance);
                        }

                        else
                        {

                            Stream stream = new MemoryStream(bytes);
                            object[] array1 = new object[9];
                            array1[0] = stream;
                            array1[1] = sharePointFile.filecontent[i]["Name"].Value;
                            array1[2] = DateTime.Now;
                            array1[3] = DateTime.Now;
                            array1[4] = AttachmentType.ATTACH_BY_VALUE;
                            array1[5] = -1;
                            array1[6] = true;
                            array1[7] = contentId;
                            array1[8] = true;
                            var ctor = typeof(MsgKit.Attachment).GetConstructors(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance).First();
                            var instance = ctor.Invoke(array1) as MsgKit.Attachment;
                            email.Attachments.Add(instance);


                        }
                    }

                    var uploads1 = Path.Combine(_environment.WebRootPath, "Uploads");
                    string guidValue = Guid.NewGuid().ToString();
                    string fileName = uploads1 + @"\email" + guidValue + ".msg";
                    email.Save(fileName);
