### ISSUE TITLE
Line breaks in html input getting lost

### ISSUE THREAD

**Issue by davidd4** [Sicos1977/MsgKit#49]
Line breaks in html input are not preserved in .msg.

The following html content
```
<div style="white-space: pre-wrap">
line1
line2
line3
</div>
```

is exported into the .msg file as
`line1line2line3`

Tested in MsgKitTestTool. See screenshots.

![image](https://user-images.githubusercontent.com/2652605/51339177-10bbd680-1a8c-11e9-844d-9fb153be598f.png)

![image](https://user-images.githubusercontent.com/2652605/51339377-993a7700-1a8c-11e9-94c5-5f9e4ccee295.png)

**Comment by Sicos1977** [comment]
This is normal HTML behavior, if you want to start on a new line you have to add the <br/> tag at the end.

line1<br/>
line2 <br/>
line3 <br/>

**Comment by davidd4** [comment]
I can't agree. The whitespaces should not be removed from the text. They are characters too.

Please try it with your suggestion:

```
<pre>
line1
line2
line3
</pre>

```

![image](https://user-images.githubusercontent.com/2652605/51411706-26eb9480-1b69-11e9-9f56-18e1c5ab99ea.png)

and the result will be the same. 

![image](https://user-images.githubusercontent.com/2652605/51411747-4682bd00-1b69-11e9-8834-b10147e22780.png)


And it's wrong. The line breaks should be preserved, but they are removed in MsgKit code, in the method: `Strings.GetEscapedRtf(BodyHtml);`

Please check the attached .html file. My code is a valid html code, and it can be opened in any browser.
[linebreaks.zip](https://github.com/Sicos1977/MsgKit/files/2774445/linebreaks.zip)

**Comment by HarbinderGill** [comment]
I should probably add, that we generate html from a docx, and then convert to html using the open xml power tools. If we take that markup and view in a browser, all line breaks are preserved. If we display in an email, some of the line breaks disappear. I've had to put in a couple of regex patterns to replace empty spans with <br/> to get around it.

**Comment by Sicos1977** [comment]
Whatever I try I just can't get outlook to show the message with the line breaks (enters). I even fixed the GetEscapedRtf method and that still gives the same problem. So I think it is an limitation in Outlook and for that I'll close this issue and something that I can't fix.

![image](https://user-images.githubusercontent.com/6692947/53747839-70d3d400-3ea4-11e9-8c46-fc8befc5e9f3.png)

**Comment by Sicos1977** [comment]
When I make a new message in Outlook and view the body then you'll see that Outlook converts my 3 lines to HTML with paragraph (p) tags in it.

![image](https://user-images.githubusercontent.com/6692947/53748078-e475e100-3ea4-11e9-882f-4bb08de71450.png)
