### ISSUE TITLE
How to save as draft?

### ISSUE THREAD

**Issue by Seddy24** [Sicos1977/MsgKit#5]
I'm looking to save the msg as a draft.  Is there a current property i'm missing that can be set or one that could be added?

Thanks!

**Comment by Sicos1977** [comment]
I did not make a property for that to set but if you modify the code then you need to change this:

`            var messageFlags = MessageFlags.MSGFLAG_UNMODIFIED;`
to this

```
            var messageFlags = MessageFlags.MSGFLAG_UNMODIFIED;
            messageFlags |= MessageFlags.MSGFLAG_UNSENT;
```

That will set the msg file as draft

**Comment by Sicos1977** [comment]
I added an option to save the email as draft

https://github.com/Sicos1977/MsgKit/commit/abfee2fe60eeae01e82eead2121016f088bb3d36
