### ISSUE TITLE
Unable to open an appointment on outlook 2013

### ISSUE THREAD

**Issue by HarbinderGill** [Sicos1977/MsgKit#51]
When using the sample code to create an appointment, the resultant .msg file opens as an email rather than an appointment when using outlook 2013. We've tried this on a few different machines.

The email sample works with no problems. Any ideas?

**Comment by Sicos1977** [comment]
Fixed in this commit 10b8dd60efa935e5264ee3c9919349bf13b7992f

**Comment by Sicos1977** [comment]
I also released a new nuget package
