### ISSUE TITLE
Setting body text to html in an email does not work

### ISSUE THREAD

**Issue by HarbinderGill** [Sicos1977/MsgKit#52]
Your last change to fix appointments worked perfectly so thank you for the quick turnaround. Unfortunately, setting the body text in an email to HTML is now broken and always goes back to setting body text as text.

**Comment by Sicos1977** [comment]
I did change nothing that shouls break that. I'll try to look into it this evening. Do you have some example code that you did write to build the email message so that I have some test cases.

**Comment by HarbinderGill** [comment]
Hi, we generate html via openxml and inject it into the email body. Our prototype was working fine yesterday, but today we can see that the bodyhtml is set to html, however its always displaying whatever is set in bodytext.

If you run your sample, do you see html or text? I'll check again later, its shelved at the moment so I just need some time to do it.

**Comment by Sicos1977** [comment]
If I run the sample I see an HTML body

![image](https://user-images.githubusercontent.com/6692947/53695189-84a20c00-3db8-11e9-9bcb-2e3bcbcb9e61.png)

**Comment by HarbinderGill** [comment]
I'll have a look at this today, I should add, has your nuget version number gone backward, i.e. from 2.1 to 2.0.2?

**Comment by HarbinderGill** [comment]
Firstly thank you for replying, and thank you for your time and effort in creating a really decent free component.

version 2.0.2 (again as per my last comment the version number in nuget went backwards):
![version](https://user-images.githubusercontent.com/48093780/53742716-30b72600-3e91-11e9-8abf-154f5dcca3d6.jpg)

source code - note that both bodytext and bodyhtml are set:
![image](https://user-images.githubusercontent.com/48093780/53742788-5e9c6a80-3e91-11e9-8dd9-61ad5d679c30.png)

On rendering the msg:

![image](https://user-images.githubusercontent.com/48093780/53742929-a3280600-3e91-11e9-9194-2c7cf2b52095.png)

**Comment by HarbinderGill** [comment]
I'll do the same test on 2.1.0 (the version in which appointments don't work):

![image](https://user-images.githubusercontent.com/48093780/53743039-dff3fd00-3e91-11e9-9f6f-423f776c6836.png)

Exactly the same code
![image](https://user-images.githubusercontent.com/48093780/53743077-f00bdc80-3e91-11e9-9fea-74d3eaa90d26.png)

![image](https://user-images.githubusercontent.com/48093780/53743165-192c6d00-3e92-11e9-8188-d1e7ab39d707.png)

Works as expected.

I'd suggest trying the nuget v2.0.2 rather than local source code just in case there is a mismatch.

**Comment by Sicos1977** [comment]
Uhm... let me try your code... and see what that does do

**Comment by Sicos1977** [comment]
> 
> 
> I'll have a look at this today, I should add, has your nuget version number gone backward, i.e. from 2.1 to 2.0.2?

That is a typo... it should have been 2.2.0 ... :-) I'll fix it when I find out why the code doesn't work in your case.

**Comment by Sicos1977** [comment]
I just made this and that seems to work as expected... it's almost the same as your code.

![image](https://user-images.githubusercontent.com/6692947/53745358-2f8cf580-3e9f-11e9-8a9a-7a7b03c5f463.png)

**Comment by HarbinderGill** [comment]
Is that version pulled from nuget? I'll uninstall the package and try again.

**Comment by Sicos1977** [comment]
I figured it out... it seems to go wrong when you set draft to **true** ... setting it to **false** fixes the issue... I now have to figure out why the code does this... I had the same problem in the past and fixed it but for some reason I got that problem back again.

![image](https://user-images.githubusercontent.com/6692947/53745609-9c07f480-3e9f-11e9-8363-36c210d8de8c.png)

**Comment by HarbinderGill** [comment]
ah perfect thank you for your efforts in tracking this down. I was going to just suggest draft mode.

**Comment by Sicos1977** [comment]
I'll have to check the code if I somehow did revert something back to an older version.

**Comment by Sicos1977** [comment]
If I remember it correctly you have to set an RTF body with the HTML encapsulated into it to fix the problem where you get text when you set the e-mail to draft.

**Comment by Sicos1977** [comment]
Adding this to the code fixes the issue with the e-mail set to draft.

![image](https://user-images.githubusercontent.com/6692947/53746022-97900b80-3ea0-11e9-97c5-ca226813c169.png)

**Comment by Sicos1977** [comment]
This commit fixes the issue 8b3d815ccd131c9caa9b1907737722ce90df3fc4

I also just released a new nuget package (2.3.0) with this fix in it. Give it 30 minutes to get indexed on nuget.
