### ISSUE TITLE
Outlook 365 

### ISSUE THREAD

**Issue by gamached** [Sicos1977/MsgKit#54]
Recently, the MSG file created by msgkit seems to be opened as read-only by Outlook 365. I believe Outlook 365 may have changed their .msg file format.

**Comment by Sicos1977** [comment]
Can you send me a file that is giving you this issue? Please send it to sicos2002@hotmail.com , please zip the msg file before sending.

**Comment by Sicos1977** [comment]
No response... closed

**Comment by brianfairchild** [comment]
I'm running into the same type of issue. If I set the Draft flag to true Outlook 365 only opens it in a read only mode. If I set Draft to true the message gets sent but it is flagged in Outlook as a draft with an icon of a page and a pencil. 

Also, I have 2.3.0 installed. I went to check for an update today and it says the latest version is 2.1.0. Is this a typo?

**Comment by brianfairchild** [comment]
I've attached two files as examples, one with Draft=True and the other omitting draft in the ctor.  This is how I am constructing my message:
using (var email = new Email(null, subject: envelope.Subject, draft:true, readReceipt:false))
                {
...
}


[DraftProblemMsgFiles.zip](https://github.com/Sicos1977/MsgKit/files/3627726/DraftProblemMsgFiles.zip)

**Comment by Sicos1977** [comment]
Version 2.3.0 should be the latest verion

![image](https://user-images.githubusercontent.com/6692947/65214188-514f7200-daa9-11e9-8c54-d32bab281c2e.png)
