### ISSUE TITLE
adding inline images

### ISSUE THREAD

**Issue by kyhubber** [Sicos1977/MsgKit#55]
Anywhere I can find examples of using inline messages with MsgKit? I am concatenating the signature file of outlook to an existing html and using that as the source for BodyHtml. I think if I knew to use inline files, I could copy or change the image as needed.

**Comment by Sicos1977** [comment]
Adding inline images is just like adding a normal image. The only difference is that you need to add an unique id en integrate this id in the html body of the mail

**Comment by kyhubber** [comment]
Thanks. If I understand, I add an attachment and specify inline=True and provide the contentid? Excellent!

**Comment by Sicos1977** [comment]
Yes thats it
