### ISSUE TITLE
Reading MSG File and Adding Attachment

### ISSUE THREAD

**Issue by ab-tools** [Sicos1977/MsgKit#56]
Hello Kees,

first thanks for the two great MSG libraries that you have here!

The task I would like to accomplish is reading an existent MSG file, adding an attachment and saving the MSG file again.

I see that your library MSGReader supports reading MSG files which works fine in my test, but unfortunately it seems this library does not support adding attachments (only deleting them).

And the library MsgKit here seems to only support creating new MSGs completely from scratch, but not loading existent ones or did I miss something?

Therefore my question:
What's the best way to load an existent MSG file, add an attachment to it and save it again?

Thanks in advance
Andreas

P. S.: Would it maybe not even make sense to combine those two libraries to one?

**Comment by VladanKostic** [comment]
Hi, maybe library from Independentsoft company can help you. 
It is Microsoft Outlook .msg file API for Java/Android/.NET Framework and it will be soon for Python, JavaScript, Node.js and other runtimes and frameworks based on JavaScript. 
The API offers Outlook functionality and there are a number of use cases on the site like:
- create message, appointment, task, contact or any other Outlook item
- Read any Outlook .msg file and get all properties
- Retreive attachments, and much more
and much more.

**Comment by ab-tools** [comment]
Well, thanks, but I don't plan to spend 300 EUR on a library for this!

Then I rather donate Kees some money to get his two great libraries here combined and have this functionality supported. :-)

**Comment by gabriel-jones** [comment]
Just wondering, is this possible at the moment with this library? That is, initializing a message using an existing .msg file

**Comment by Sicos1977** [comment]
No that is not possible. If you want to do that you can read the MSG file with MSGReader and then create a new MSG file with MSGKit. It should not be to hard to do that in code.
