### ISSUE TITLE
Convert Graph.Message To Email

### ISSUE THREAD

**Issue by DineshLalchand** [Sicos1977/MsgKit#57]
Hi,
I am trying to convert Microsoft.Graph.Message to MsgKit.Email so that i can save the email as .msg file. Images does not appear in my .msg file. Please educate me as what i am missing. 

Below is the code snippet.

var email = new Email(new Sender(message.Sender.EmailAddress.Address, message.Sender.EmailAddress.Name), message.Subject);

                email.SentOn = DateTimeOffset.Parse(message.SentDateTime.ToString()).DateTime;
                email.ReceivedOn = DateTimeOffset.Parse(message.ReceivedDateTime.ToString()).DateTime;
                email.InternetMessageId = message.InternetMessageId;

                //Importance
                switch (message.Importance)
                {
                    case Importance.Low:
                        email.Importance = MessageImportance.IMPORTANCE_LOW;
                        break;
                    case Importance.Normal:
                        email.Importance = MessageImportance.IMPORTANCE_NORMAL;
                        break;
                    case Importance.High:
                        email.Importance = MessageImportance.IMPORTANCE_HIGH;
                        break;
                }

                //To
                foreach (var to in message.ToRecipients)
                {
                    email.Recipients.AddTo(to.EmailAddress.Address, to.EmailAddress.Name);
                }

                //Cc
                foreach (var cc in message.CcRecipients)
                {
                    email.Recipients.AddCc(cc.EmailAddress.Address, cc.EmailAddress.Name);
                }

                //Bcc
                foreach (var bcc in message.BccRecipients)
                {
                    email.Recipients.AddBcc(bcc.EmailAddress.Address, bcc.EmailAddress.Name);
                }

                switch (message.Body.ContentType)
                {
                    case BodyType.Text:
                        email.BodyText = message.Body.Content;
                        break;
                    case BodyType.Html:
                        email.BodyHtml = message.Body.Content;
                        break;
                    default:
                        email.BodyText = message.Body.Content;
                        break;
                }

                if (message.HasAttachments == true)
                {
                    foreach (dynamic attachmentFile in message.Attachments)
                    {
                        if (attachmentFile.ODataType.ToLower() == ("#microsoft.graph.fileAttachment").ToLower())
                        {
                            var fileStream = new MemoryStream(attachmentFile.ContentBytes);
                            email.Attachments.Add(fileStream, attachmentFile.Name, -1, attachmentFile.IsInline, attachmentFile.Id);
                        }
                        else if (attachmentFile.ODataType.ToLower() == ("#microsoft.graph.itemAttachment").ToLower())
                        {

                            email.Attachments.Add(attachmentFile.Name, -1, attachmentFile.IsInline, attachmentFile.Id);
                        }
                    }
                }

**Comment by Sicos1977** [comment]
Can you send me the e-mail that is giving you this problem? If so then please send it to sicos2002@hotmail.com

**Comment by Sicos1977** [comment]
No response... closed
