### ISSUE TITLE
Reply To adress

### ISSUE THREAD

**Issue by madrianr** [Sicos1977/MsgKit#59]
Hello, is it possible to add a reply to adress?

robert

**Comment by madrianr** [comment]
Please is it possible to get an answer?

robert

**Comment by madrianr** [comment]
i set the floowing but it doesn't work:

                email.TransportMessageHeaders = new MessageHeader();
                email.TransportMessageHeaders.SetHeaderValue("Reply-To", "test@test.or.at");

I save the message in draft mode and open it with Outlook...

**Comment by Sicos1977** [comment]
I forgot you issue, ill try to look into it this week

**Comment by madrianr** [comment]
some news about that?

**Comment by Sicos1977** [comment]
I'm building it at this moment :-)

**Comment by Sicos1977** [comment]
Please check if this works --> https://github.com/Sicos1977/MsgKit/commit/ae0cfd4add3b24f0f69f1c6102235693345987c1

If not then I have to figure out how to fill the PR_REPLY_RECIPIENT_ENTRIES property

**Comment by madrianr** [comment]
is there a new Nuget Package available?

 

I use ASP.NET Core and need a Nuget Package ;-)

 

Von: Kees [mailto:notifications@github.com] 
Gesendet: Mittwoch, 13. November 2019 16:42
An: Sicos1977/MsgKit
Cc: Robert Madrian (madrian e-dbsolutions); Author
Betreff: Re: [Sicos1977/MsgKit] Reply To adress (#59)

 

Please check if this works --> ae0cfd4 <https://github.com/Sicos1977/MsgKit/commit/ae0cfd4add3b24f0f69f1c6102235693345987c1> 

If not then I have to figure out how to fill the PR_REPLY_RECIPIENT_ENTRIES property

**Comment by madrianr** [comment]
What do you mean with "Please check if this works --> ae0cfd4" - what should I test/do?

**Comment by madrianr** [comment]
it works now with:
                    email.ReplyToRecipients.AddRecipient(txtMail_Outlook_ReplyTo, txtMail_Outlook_ReplyTo, AddressType.Unknown, RecipientType.To);

thanks
