### ISSUE TITLE
Font in BodyHtml?

### ISSUE THREAD

**Issue by madrianr** [Sicos1977/MsgKit#66]
Hello,

If I create a draft message with the following BodyHtml - how to set the font of the text (best practice)?
email.BodyHtml = `"<html><head></head><body>Test</body></html>"`

or how does Outlook set the font because if I open the message with Outlook a specific font is set like TimesNewRoman...

robert

**Comment by Sicos1977** [comment]
You can just set the font like the way you do it in html. If you don't set a font outlook will use its default font.

https://www.w3schools.com/tags/tag_font.asp
