### ISSUE TITLE
The attachment with the name already exists

### ISSUE THREAD

**Issue by tbgrewal** [Sicos1977/MsgKit#72]
Hi I love your application and it has been working very well for a long time. However today I came across an unusual happening. An email does not have any attachments but there are 2 .png images with the same name within the body of the email. MsgKit reacts with an error complaining the name XXX.png  already exists. How can I take care of this? Any suggestions or solution would be greatly appreciated. Thanks.

**Comment by Sicos1977** [comment]
Fixed with this commit e6095f94e59ef89feecc541b880b6a9bae1be6b6
