### ISSUE TITLE
add option when adding Any file to the attachments to be able to pass along the mimetype

### ISSUE THREAD

**Issue by avck25** [Sicos1977/MsgKit#73]
When I am adding a docx file to an attachment it is not rendering properly 
so to be able to pass along to the new Attachment created the Mime type of `application/vnd.openxmlformats-officedocument.wordprocessingml.document` for the docx file

**Comment by Sicos1977** [comment]
I dont understand the problem. I just added a docx attachment myself and the correct mimetype is set.

![image](https://user-images.githubusercontent.com/6692947/87874907-d2c7a780-c9cd-11ea-97bc-70569391ad25.png)
