### ISSUE TITLE
Email Dispose() throws NullReferenceException if Email not saved

### ISSUE THREAD

**Issue by kganjam** [Sicos1977/MsgKit#74]
Email Dispose() throws NullReferenceException if there has not been a call to Save(). 

NullReferenceException: Object reference not set to an instance of an object.

Repro:
```
using (var email = new Email(
          new Sender("x@y.com", "x"),
          new Representing("x@y.com", "x"),
          "subject", 
          false))
{	
} 
// throws on Dispose()
```

This came up when using the code above inside a function that would "yield return" emails. If the caller didn't call Save(), then things would break. 

```
IEnumerable<Email> GenerateEmails()
{
   using (var email = new Email(...))
   {
       yield return email;
   }
}
```

**Comment by Sicos1977** [comment]
This issue should be fixed with this commit 6cb707ab62b4c688ab14c0950dd34109a7e92b53
