### ISSUE TITLE
Create a message and adding property "BillingInformation"?

### ISSUE THREAD

**Issue by SigiKoh** [Sicos1977/MsgKit#78]
i am sorry - as a beginner, i do not understand how i can add additional properties to a message... :-(
any existing documentation oder samples?
THX

**Comment by Sicos1977** [comment]
You can use the AddProperty method for that

![image](https://user-images.githubusercontent.com/6692947/105625516-2a861600-5e2a-11eb-952e-8faae15dc06f.png)

**Comment by SigiKoh** [comment]
Sorry, it's me again ... :-)  But how to add a Property with longId?
PidLidBilling - Property long ID (LID): 0x00008535
THX for help ...
