### ISSUE TITLE
Attachment with PidTagAttachMethod = 0x00000007 - ByWebReference

### ISSUE THREAD

**Issue by DoubleAxion** [Sicos1977/MsgKit#79]
Goeie middag Kees

Thank you for all of your hard work!

I need to create an attachment where the byte content is hosted as an Internet resource.
I am creating a PST file from email on Office 365 Exchange, and some of the attachments are references to an Office 365 xls attachment hosted on the server.

The attachment is marked as Hidden (Inline) (0x7FFE) and there is no binary content for it, and the web URL is then derived from AttachmentLongPathname (0x370D).

Reference is found here: https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxcmsg/252923d6-dd41-468b-9c57-d3f68051a516

I am hoping to do something like this:
`
msgKitEmail.Attachments.AddWebLink(filename, longPathname, contentId);
`

The closest I can find is "AddLink" which takes a FileInfo object, hoping that ATTACH_BY_REF_ONLY would work, but it seems that ATTACH_BY_WEB_REFERENCE is needed after all.

Asseblief my ou groot maat! :)

**Comment by Sicos1977** [comment]
I'll will add the option. Will try to look in to it tomorrow.

**Comment by DoubleAxion** [comment]
Thank you so much Kees – you ROCK dude!

 

Kerry

**Comment by Sicos1977** [comment]
Do you maybe have an example e-mail? I need to figure out what properties need to be added to an msg file to make this work. I looked up the PidNameAttachmentProviderType tag but can't find the infrmation that I need.

**Comment by DoubleAxion** [comment]
I’ll send you an awesome example.

 

Give me a few minutes while I test something out for ya.

 

I’ll send you the email with an attachment, and I’ll send a separate email with the equivalent FTS binary and it’s breakdown.

 

Kerry

**Comment by DoubleAxion** [comment]
Attached are the following:

1.	The original email “Web Reference Attachment”
2.	The FTS binary of the email “Web Reference Attachment.fts”
3.	The interpreted form of the FTS binary “Web Reference Attachment.txt” which is my own disassembly format of the binary

a.	The point of interest is line 520 to 538 of the txt starting from “NewAttach”
b.	Each line represents one field.  If the field type is known then the type (i.e PtypInteger32 or PtypBinary etc) is displayed and the same goes for the field name (i.e. PidTagAttachNumber or PidTagAttachFilename etc).  If the field type is NOT known, then the decimal number is shown.  Line 536 has the field PidNameAttachmentProviderType which is 0x8953, which was not known at the time the attached FTS disassembly was emitted.

 

Please let me know if there is anything I can help you with.

 

Kerry

**Comment by Sicos1977** [comment]
0x8953 is a named property, is it possible to sent me the msg file itself? If yes then zip it before sending it to sicos2002@hotmail.com
