### ISSUE TITLE
create Contact .msg

### ISSUE THREAD

**Issue by ProxBiz** [Sicos1977/MsgKit#82]
Hello,
Any chance of implementing or a hint on how to create a Contact .msg file with this library. 
Wanted to extend it myself but having problems. 
Regards

**Comment by Sicos1977** [comment]
Do you have an example file so that I can have a look inside?

**Comment by ProxBiz** [comment]
In my trials I have kind of made a contact. I could read the content with MSTReader from your other repository but when double clicking and opening with outlook I receive a Could not read Item warning.
Tried putting together some things from the MSGReader and look at the FileStream but I couldn`t convert to something that I understand.
I have attached a contact with all the properties from outlook as .msg and .msg unicode.
Thank you for the response and help.

[contact.zip](https://github.com/Sicos1977/MsgKit/files/6159111/contact.zip)

**Comment by ProxBiz** [comment]
Any updates or some documentation you can refer me so I can try it myself ? 
Regards

**Comment by Sicos1977** [comment]
Sorry about the late response (to busy with work).

What I would do is;

- Clone MsgKit
- Add a class called Contact with Email as it base (Contact : Email)
- Download Outlook Spy (https://dimastr.com/outspy/download.htm) ... you have a 30 day trail version
- Look inside the contact msg file to see what properties are added by Outlook to make this work

![image](https://user-images.githubusercontent.com/6692947/113179937-71d8ba80-9250-11eb-804e-31eb17db989d.png)

- Overwrite the WriteToStorage method like how it is done in the Appointment class, set all the properties that are needed

```c#
#region WriteToStorage
        /// <summary>
        ///     Writes all the properties that are part of the <see cref="Appointment"/> object either as <see cref="CFStorage"/>'s
        ///     or <see cref="CFStream"/>'s to the <see cref="CompoundFile.RootStorage"/>
        /// </summary>
        private new void WriteToStorage()
        {
            Class = MessageClass.IPM_Appointment;
            NamedProperties.AddProperty(NamedPropertyTags.PidLidLocation, Location);
            NamedProperties.AddProperty(NamedPropertyTags.PidLidAppointmentStartWhole, MeetingStart);
            NamedProperties.AddProperty(NamedPropertyTags.PidLidAppointmentEndWhole, MeetingEnd);
            NamedProperties.AddProperty(NamedPropertyTags.PidLidMeetingType, MeetingType.mtgRequest);
            NamedProperties.AddProperty(NamedPropertyTags.PidLidAppointmentSubType, AllDay);
            NamedProperties.AddProperty(NamedPropertyTags.PidLidAppointmentStateFlags, AppointmentState.asfMeeting);
        }
        #endregion
```

- Set the Class property to (IPM.Contact) ... you need to add this enum

Create the MSG file and see If Outlook wants to open it without errors

**Comment by Sicos1977** [comment]
I already made a start with the Contact class to show you how it is done. If you need any help then just post a question in this issue

**Comment by Sicos1977** [comment]
@ProxBiz : You can stop your own effort (if you even started :-) ) I'm about 80 procent done with implementing the contact card. With some luck it will be finished next week.

**Comment by ProxBiz** [comment]
Haha, thanks for the heads up, i was 30% in the process. Wanted to follow your good coding practice so i can branch and merge my changes.
I will be following the next updates. Thanks and have a great weekend.

**Comment by Sicos1977** [comment]
Thank you for the coding practice complement.

**Comment by Sicos1977** [comment]
All the properties are added, now it will be testing test and testing to make everything work and keep Outlook happy. Feel free to test.

**Comment by ProxBiz** [comment]
looks good on my end, can you post new nugget package ?

**Comment by Sicos1977** [comment]
Not now because everything is not working as it should, that needs to be fixed first.

**Comment by Sicos1977** [comment]
I hope to finish the contact option this week, work was to busy to do anything last week.

**Comment by ProxBiz** [comment]
No problem, i understand you have other things to do. Take your time
