### ISSUE TITLE
Save as Stream is missing the CFBF header when compared to Save as Filename

### ISSUE THREAD

**Issue by jerdobi** [Sicos1977/MsgKit#86]
If you save as a stream the email the CFBF header is missing and when you use the stream to create a file this file cannot be opened by Outlook because the header is missing.
[Documents.zip](https://github.com/Sicos1977/MsgKit/files/7200022/Documents.zip)

**Comment by Sicos1977** [comment]
Work fine if I do something like this

```csharp
using (var ms = new MemoryStream())
{
    email.Save(ms);
    File.WriteAllBytes("d:\\test2.msg", ms.ToArray());
}
```

**Comment by Sicos1977** [comment]
I even can't use the Stream class because it is abstract. And if you have an issue with saving then you should contact the OpenMCDF project because that is what I use to do the saving.

https://github.com/ironfede/openmcdf
