### ISSUE TITLE
PR_SENSITIVITY property length

### ISSUE THREAD

**Issue by Mystercoco** [Sicos1977/MsgKit#89]
The property is using 4 bytes causing Outlook to crash when opening the msg file; it should be on 8 bytes instead.

A simple fix is to change the type in the file PropertyTags.cs as following (line 533)
<syntaxhighlight lang="C#" line>
public static PropertyTag PR_SENSITIVITY
        {
            get { return new PropertyTag(0x0036, PropertyType.PT_I8); }
        }
</syntaxhighlight>

**Comment by Sicos1977** [comment]
According to Microsoft it should be a long.

https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/pidtagsensitivity-canonical-property

And it is a long in code
```

        /// <summary>
        ///     Contains a value indicating the message sender's opinion of the sensitivity of a message.
        /// </summary>
        public static PropertyTag PR_SENSITIVITY
        {
            get { return new PropertyTag(0x0036, PropertyType.PT_LONG); }
        }
```

So nothing to fix

**Comment by Mystercoco** [comment]
I had an error message when adding Sensitivity property (see screenshot below), changing the code to 8 bytes fixed it.
The documentation is showing example values for PidTagSensitivity on 8 bytes, like here https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/pidtagrecipientreassignmentprohibited-canonical-property
So maybe it's an error in the doc or an issue with my Outlook (2016).
<img width="463" alt="20211103 Sensitivity" src="https://user-images.githubusercontent.com/384157/140170572-43529a6f-2df9-4d1a-9e87-1ad99076fc67.PNG">
