### ISSUE TITLE
Convert EML file with MSG attachment to MSG file, the attachment becomes EML format

### ISSUE THREAD

**Issue by sang2357** [Sicos1977/MsgKit#91]
Referring to the issue [#issue-1246285318](https://github.com/Sicos1977/MsgKit/issues/90#issue-1246285318), is the method `ConvertEmlToMsg` in [Converter.cs](https://github.com/Sicos1977/MsgKit/tree/master/MsgKit/Converter.cs) always set the attachment to extension eml, even the attachment is a msg?

```
if (bodyPart is MessagePart messagePart)
{
    messagePart.Message.WriteTo(attachmentStream);
    if (messagePart.Message != null)
        fileName = messagePart.Message.Subject;

    extension = ".eml";
}
```

**Comment by Sicos1977** [comment]
This is probably not going to happen anymore so I'm closing this issue
