### ISSUE TITLE
winmail.dat

### ISSUE THREAD

**Issue by FunnyPaul** [Sicos1977/MsgKit#95]
One thing in advance: excellent work! Thanks very much!

If I create a simple e-mail with an attachment and HTML-formatted text, Outlook always sends it with TNEF, i.e. everything is packed in a "_winmail.dat_" again. As is well known, a few clients still have problems with this.

Is there a way to turn this off so that a **true multipar**t email is created/sent?

**Comment by Sicos1977** [comment]
When something is converted to winmail.dat this is because of a wrong setting on the Exchange server. This has nothing todo with MsgKit

**Comment by FunnyPaul** [comment]
Thank you for the fast reaction.

If I simply create an email in Outlook (with text formatting) and send it, no '_winmail.dat_' is created.

When I create an MSG file with the trial version of Apose.E-Mail for NET, with HTML body content, no '_winmail.dat_' is generated either.

So I don't think it's the Exchange server. It's the same with Office 365.

**Comment by Sicos1977** [comment]
In that case please make an email with Aspose.E-Mail for NET and one with MSG kit with the exact samen content and then e-mail them to sicos2002@hotmail.com so that I can figure out what the difference is. Please ZIP the files before sending them.

**Comment by FunnyPaul** [comment]
You have mail :-)

**Comment by BojownikZKosmosu** [comment]
Load the message as a MimeMessage, then extract the Tnef part, decode it, and then load this part as another MimeMessage to access the entire message.

`var mimeMessage = await MimeMessage.LoadAsync(stream);
 stream.Seek(0, SeekOrigin.Begin);
 var winMailDat= mimeMessage.BodyParts.OfType<TnefPart>().First();
using var decodedStream = new MemoryStream();
 await winMailDat.Content.DecodeToAsync(decodedStream);
 decodedStream.Seek(0, SeekOrigin.Begin);
  var winMailDatEmail= await MimeMessage.LoadAsync(decodedStream);`

**Comment by ksn65** [comment]
I have a very similar situation. What was the conclusion regarding this issue? Was there a fix or workaround possible?

**Comment by cobrul** [comment]
I have a similar situation, I generate emails with the code below, sometimes they arrive as winmail.dat (but only sometimes, I asked the user to generate and send me again the email and I received the proper format).. what was the conclusion regarding this issue ?

```csharp
using var email = new MsgKit.Email(null, "", true);

email.MessageEditorFormat = MsgKit.Enums.MessageEditorFormat.EDITOR_FORMAT_HTML;

email.BodyHtml = htmlText;
email.BodyText = plainText;
```
