### ISSUE TITLE
Property PidLidReminderSet has wrong type

### ISSUE THREAD

**Issue by ImKrian** [Sicos1977/MsgKit#97]
Hello, thank you for this tool

I generated some appointments and tried to update the configured alert of the appointments to 5 minutes but I was unable to do so, the property _ReminderSet_ is always set to FALSE.

I believe there is an error in the configuration of the _PidLidReminderSet_ property in the file [NamedPropertyTags.cs](https://github.com/Sicos1977/MsgKit/blob/master/MsgKit/NamedPropertyTags.cs) at line 2324. According to the [documentation](https://learn.microsoft.com/en-us/office/client-developer/outlook/mapi/pidlidreminderset-canonical-property) this property type is PT_BOOLEAN while it is currently configured as PT_LONG.

**Comment by Sicos1977** [comment]
Fixed in one of the latest commits
